/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
"use strict";import messageHandler from"./message-handler.js";function sendDomainInformationMessage(e){const{requestId:s,_sender:n}=e;messageHandler.sendMessageToSender({type:"DOMAIN_INFORMATION",requestId:s,timestamp:Date.now(),payload:{domain:window.location.hostname}},n)}function sendMutationObserverEventMessage(e,s){messageHandler.sendMessageToSender({type:"MUTATION_OBSERVER_EVENT",requestId:e,timestamp:Date.now(),payload:{}},s)}function sendElementFoundMessage(e,s,n,t,a){messageHandler.sendMessageToSender({type:"ELEMENT_FOUND",requestId:e,timestamp:Date.now(),payload:{getElementBy:n,className:t,elementDetails:a}},s)}function sendElementNotFoundMessage(e,s,n,t){messageHandler.sendMessageToSender({type:"ELEMENT_NOT_FOUND",requestId:e,timestamp:Date.now(),payload:{getElementBy:n,selector:t,error:`Element not found using strategy: ${n} with selector: ${t}`}},s)}function sendElementsFoundMessage(e,s,n,t,a){messageHandler.sendMessageToSender({type:"ELEMENTS_FOUND",requestId:e,timestamp:Date.now(),payload:{getElementBy:n,selector:t,elementsDetails:a,count:a.length}},s)}function sendElementsNotFoundMessage(e,s,n,t){messageHandler.sendMessageToSender({type:"ELEMENTS_NOT_FOUND",requestId:e,timestamp:Date.now(),payload:{getElementBy:n,selector:t,error:`No elements found using strategy: ${n} with selector: ${t}`,count:0}},s)}function sendEventHandlerEventMessage(e,s,n,t){messageHandler.sendMessageToSender({type:"EVENT_HANDLER_EVENT",requestId:e,timestamp:Date.now(),payload:{eventHandlerType:n,targetNodeSelector:t}},s)}function sendSessionDataMessage(e,s,n){messageHandler.sendMessageToSender({type:"SESSION_DATA",timestamp:Date.now(),payload:{sessionData:n},requestId:e},s)}function sendDownloadBufferFromUrlResponseMessage(e,s,n){messageHandler.sendMessageToSender({type:"DOWNLOAD_BUFFER_FROM_URL_RESPONSE",requestId:e,timestamp:Date.now(),payload:{buffer:n}},s)}function sendGetStorageValueResponse(e,s,n,t,a){messageHandler.sendMessageToSender({type:"GET_STORAGE_VALUE_RESPONSE",requestId:e,timestamp:Date.now(),payload:{storageType:n,data:t,error:a||null}},s)}function sendSetStorageValueResponse(e,s,n,t,a){messageHandler.sendMessageToSender({type:"SET_STORAGE_VALUE_RESPONSE",requestId:e,timestamp:Date.now(),payload:{storageType:n,success:t,error:a||null}},s)}export default{sendDomainInformationMessage:sendDomainInformationMessage,sendMutationObserverEventMessage:sendMutationObserverEventMessage,sendElementFoundMessage:sendElementFoundMessage,sendElementNotFoundMessage:sendElementNotFoundMessage,sendElementsFoundMessage:sendElementsFoundMessage,sendElementsNotFoundMessage:sendElementsNotFoundMessage,sendEventHandlerEventMessage:sendEventHandlerEventMessage,sendSessionDataMessage:sendSessionDataMessage,sendDownloadBufferFromUrlResponseMessage:sendDownloadBufferFromUrlResponseMessage,sendGetStorageValueResponse:sendGetStorageValueResponse,sendSetStorageValueResponse:sendSetStorageValueResponse};